kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      hostname: nfs-server
      containers:
      - name: nfs-server
        image: gcr.io/eventyay/nfs-server:latest
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
#        volumeMounts:
#          - mountPath: /data
#            name: data-pvc
#      volumes:
#        - name: data-pvc
#          persistentVolumeClaim:
#            claimName: nfs-data-claim
